apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  tomcat-deployment
  namespace: backbase
  labels:
    name:  tomcat-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
    #The maximum number of pods that can be scheduled above the desired number of pods. 
      maxSurge: 1
    #The maximum number of pods that can be unavailable during the update. Value can be an absolute number
      maxUnavailable: 1
    #Type of deployment. Can be "Recreate" or "RollingUpdate". Default is RollingUpdate
    type: RollingUpdate
  template:
    metadata:
        labels:
          name: tomcat
    spec:
      containers:
      - image: shahabshahab2/backbase_tomcat:8
        name:  tomcat-container
        imagePullPolicy: IfNotPresent
 #Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, 
        #it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value
        resources:
          requests:
            cpu: "10m"
            memory: "32M"
        ports:
        #Number of port to expose on the pod's IP address
        - containerPort:  8090
          name:  tomcat-web-port
      restartPolicy: Always


