apiVersion: v1
kind: Service
metadata:
  name: tomcat-expose-service
  namespace: backbase
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32752
  selector:
    name: tomcat